[tools]
node = "24"
"npm:diff2html-cli" = "latest"
"npm:diffity" = "latest"
"npm:npm-check-updates" = "latest"
pnpm = "latest"
python = "3"
ruby = "4"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
